### ISSUE TITLE
download only specific language data from wet files like Warc

### ISSUE THREAD

**Issue by aliebrahiiimi** [commoncrawl/cc-pyspark#29]
I can query on Warc files and find positions of Persian language, but I want just text of it specifically wet file of them,
is there any option for language filter on wet files?

**Comment by sebastian-nagel** [comment]
Hi, @aliebrahiiimi - sorry this issue was lost somehow. Unfortunately, Common Crawl does not provide an index to WET or WAT files. However, since [May/June 2020](https://commoncrawl.org/2020/06/may-june-2020-crawl-archive-now-available/) the WET files include the language tags. Not as ideal for languages which occur rarely in Common Crawl. But maybe an option if you cannot afford to use the WARC records via the index (and parse the HTML to extract the plain text).
